### ISSUE TITLE
[Feature Request] Type Converters

### ISSUE THREAD

**Issue by leandro-manifesto** [nartc/mapper#237]
Hey there. I've been searching for a library to handle the data conversion for a while and found this.
Unfortunaly it is missing the Type Converters compared to the .NET version.

For example, I would like to be able to convert between `luxon`'s `DateTime` and `@google-cloud/firestore`'s `Timestamp` without having to define the mappings for every field manually. From my understanding that's what Type Converters are for.

I figured I could try to implement it and send a PR, but I found that code was too complicated for my tastes, so I decided to open an issue instead.

Is there some work on this direction?

**Comment by nartc** [comment]
TypeConverters are particularly tricky to implement with TypeScript since TypeScript's Reflection capability is very lacking. The code base, as of the moment, does not prepare for type converters support which makes it even harder to ask for PR to be honest :(

For this case, the best route to go is ValueConverter and manually mapping those fields. `createMap()` and `forMember()` returns a `CreateMapFluentFunction` so you can try create a function that wraps around it like:
https://github.com/angular-vietnam/jira-clone-angular/blob/feature/github-signin/ngvn/libs/api/mappings/src/lib/project-issue.profile.ts#L86
https://github.com/angular-vietnam/jira-clone-angular/blob/feature/github-signin/ngvn/libs/api/mappings/src/lib/utils/ignore-base-properties.util.ts

In addition, I'm working on a complete refactor for `@nartc/automapper` into `@automapper/core` with a plugin system so it's easier to scale (Timeline is TBD). Thanks for opening the request but I'm sad to say I have to close this.

**Comment by rajneeshmith** [comment]
![image](https://user-images.githubusercontent.com/86954820/125039915-a8766a80-e0b4-11eb-956c-2aecd7d4275a.png)


![image](https://user-images.githubusercontent.com/86954820/125039947-b1ffd280-e0b4-11eb-83bd-b10559498a46.png)

![image](https://user-images.githubusercontent.com/86954820/125040019-c3e17580-e0b4-11eb-825a-8c263f67290d.png)

![image](https://user-images.githubusercontent.com/86954820/125040052-cf34a100-e0b4-11eb-8cf3-e17b9342a1dc.png)


`forMember` with custom `converter` is also not working


Errror

```
2021-07-09 12:43:19.730 error uncaughtException: Value for argument "seconds" is not a valid integer.
Error: Value for argument "seconds" is not a valid integer.
```

**Comment by nartc** [comment]
@rajneeshmith hi, can you open a new issue with that info? That seems to be s bug with how to handle instantiation of classes that might have required parameters, rather than Converter
