### ISSUE TITLE
Inject into custom profile class

### ISSUE THREAD

**Issue by patrykdawid** [nartc/mapper#242]
Hi!
Short question: can (how) it is possible to inject into the profile (class extends ProfileBase) an additional object apart from the mapper?

**Comment by nartc** [comment]
At the moment, no. If you want to have external services to interfere with the mapping, then try `beforeMap` and/or `afterMap` instead.

Not saying that this is not needed but at the moment, I'm working on some core stuffs to plan for the next release which I'm not going to be able to add more features.

**Comment by patrykdawid** [comment]
I understand that there is no time now - such a profession :)

Will you enter the library development in this respect on the TODO list? I am happy to download an update of the new version with this functionality in the future!

Do you have a list of things to come in the near future somewhere? You wrote that you were working on something.

Back to my topic:
You are suggesting that I use 'beforeMap'. How does that help me? This function is also declared in the profile class.

**Comment by nartc** [comment]
@patrykdawid Yup. The Profile rework is on the agenda. For a list of things, I can share a little bit:

- AutoMapper will be in a monorepo
- AutoMapper will provide a core lib, a classes plugin (to map with classes, exactly like AutoMapper does today, with some improvements), an interfaces plugin (to map with plain objects which mean you can map with interfaces), and a Nest wrapper.
- AutoMapper will also accept custom plugin (plugin-based) and there will be documentation on how to
- Better typings and overall improvements

Here's the list off top of my head (because I don't write this down anywhere lol). About your question, `beforeMap/afterMap` (or MapAction) can be a part of a Mapping or they can be a part of a single Map operation. Since you cannot inject external services into the Profile, you'd have to lean on *single-map operation* Map Action

```ts
.map(sourceObject, DestinationModel, SourceModel, {
   beforeMap: (source, destination) => {
      // you can mutate the destination here.
   },
   afterMap: (source, destination) => {
      // you can mutate the destination here.
   }
})
```
If you want to reuse the logic for `beforeMap` and `afterMap`, make it a reusable function.

**Comment by patrykdawid** [comment]
Thank you!
The wishlist is great :) Good luck!

**Comment by patrykdawid** [comment]
PS
Information about using `beforeMap` and` afterMap` when calling `map` is missing or I did not find it, and doing this is actually a workaround for my problem.

**Comment by nartc** [comment]
@patrykdawid the information about Map Callbacks is in https://automapper.netlify.app/docs/usages/features/callbacks . Glad that it helped you out as a workaround.

**Comment by nartc** [comment]
@patrykdawid check out the new `@automapper/nestjs`. This should be possible now.
