### ISSUE TITLE
How to map arrays of objects

### ISSUE THREAD

**Issue by johnpankowicz** [nartc/mapper#259]
How can an array of objects on the source be mapped into an array of objects on the destination? I tried searching the documentation and the prior issues for clues on how to do this.

I modified the example in the docs introduction so that the "Bio" contains an array of "Jobs". To keep it simple, I add a "JobDto" interface and BioDto contains an array of "JobDto".

Below is my modified code.  Please note that in the CreateMap for BioDto, I add a extra "forMember" call.  I didn't expect this to work as is. But am I proceeding in the correct direction?

```
import { createMetadataMap, pojos } from "@automapper/pojos";
import {
  createMapper,
  CamelCaseNamingConvention,
  mapFrom
} from "@automapper/core";

export interface Job {
  title: string;
  salary: number;
}

export interface Bio {
  jobs: Job[];
  birthday: Date;
  avatarUrl: string;
}

export interface User {
  firstName: string;
  lastName: string;
  username: string;
  password: string;
  bio: Bio;
}

export interface JobDto {
  title: string;
  salary: number;
}

export interface BioDto {
  jobs: JobDto[];
  birthday: string;
  avatarUrl: string;
}

export interface UserDto {
  firstName: string;
  lastName: string;
  fullName: string;
  username: string;
  bio: BioDto;
}

export class Sample2Mapper {

  mapper = createMapper({
    name: "blah",
    pluginInitializer: pojos
  });

  useMapper() {

    this.mapBio();

    this.mapUser()

    const user: User = this.getUser();

    const userDto = this.mapper.map(user, "UserDto", "User");

  }
  mapBio() {
    createMetadataMap<Job>("Job", {
      title: String,
      salary: Number
    });

    createMetadataMap<JobDto>("JobDto", {
      title: String,
      salary: Number
    });

    createMetadataMap<Bio>("Bio", {
      avatarUrl: String
    });

    createMetadataMap<BioDto>("BioDto", {
      avatarUrl: String
    });

    this.mapper
      .createMap<Bio, BioDto>("Bio", "BioDto", {
        namingConventions: new CamelCaseNamingConvention()
      })
      .forMember(
        destination => destination.birthday,
        mapFrom(source => source.birthday.toDateString())
      ).forMember(
        destination => destination.jobs,
        mapFrom(source => source.jobs)
      );
  }

  mapUser() {
    createMetadataMap<User>("User", {
      firstName: String,
      lastName: String,
      username: String,
      bio: "Bio"
    });

    createMetadataMap<UserDto>("UserDto", "User", {
      fullName: String,
      bio: "BioDto"
    });

    this.mapper
      .createMap<User, UserDto>("User", "UserDto")
      .forMember(
        destination => destination.fullName,
        mapFrom(source => source.firstName + " " + source.lastName)
      );
  }

  getUser(): User {
    const user = {
      bio: {
        jobs: [
          {
          title: "dev",
          salary: 1234567
          },
          {
            title: "mgr",
            salary: 7654321
          }
        ],
        birthday: new Date(),
        avatarUrl: "url.com"
      },
      firstName: "Chau",
      lastName: "Tran",
      username: "ctran",
      password: "123456"
    } as User;
    return user;
  }
}
```

**Comment by nartc** [comment]
@johnpankowicz an array of objects will just be mapped *automatically* if it follows convention. I'll take the example above and modify it a little bit. Let's examine the following:
- We want to change `Bio#job` to `Bio#jobs`
- We want to map `Bio#jobs` to `BioDto#jobs`
- To keep things simple, we'll add `JobDto` for `BioDto#jobs`.

With those in mind, our models are going to look like:

```ts
export interface Job {
   title: string;
   salary: number;
}

export interface JobDto {
   title: string;
   salary: number;
}
```
so far, our `Job` and `JobDto` are **conventionally matching**.

```ts
export interface Bio {
   jobs: Job[]; // <- change to array of Job
   // snip
}

export interface BioDto {
   jobs: JobDto[]; // <-replace jobTitle and jobSalary 
   // snip
}
```

our `Bio` and `BioDto` are also **conventionally matching**. Next thing we need to do is to provide the updated metadata to AutoMapper

```ts
createMetadataMap<Job>("Job", {...}); // <-- Job should stay the same
createMetadataMap<JobDto>("JobDto", "Job"); // JobDto is exactly the same as Job so we will use `"Job"` metadata

createMetadataMap<Bio>("Bio", {
   jobs: "Job" // <-- we need to update this from "job" to "jobs"
   // snip
});
createMetadataMap<BioDto>("BioDto", {
   jobs: "JobDto" // <-- do the same thing for BioDto#jobs
   // snip
})

// User's metadata stay the same
```

At this point, we've prepared enough things for AutoMapper to do its work. Here's the analysis of what will happen when we want to map `User -> UserDto`
- AutoMapper sees `bio` and will try to map `bio` with `Mapping<Bio, BioDto>` (1)
- AutoMapper sees `jobs` when it maps `Bio -> BioDto` and will try to map `jobs` with `Mapping<Job, JobDto>` (2). Because the `sourceObj.bio.jobs` is an Array at runtime so AutoMapper will know that it needs to map a `Job[]` to `JobDto[]` **automatically**.

For (1), the current code in Stackblitz should fulfill this aka we create a `Mapping<Bio, BioDto>` with `mapper.createMap("Bio", "BioDto")`

For (2), we need to create a `Mapping<Job, JobDto>` now with `mapper.createMap("Job", "JobDto")` and that's all we need to do. Everything should map correctly now.

Check this stackblitz: https://stackblitz.com/edit/typescript-automapper-jlxuv8

**Comment by johnpankowicz** [comment]
Thanks a lot for the clear explanation and especially for the stackblitz example! It is always great to see an actually working example. In my attempts to get this working, what I was always missing was the createMap<Job, JobDto>.

The docs for POJOs appear fine. My main problem was that I didn't know it was even possible to map arrays using POJOs or even with Classes. I searched all the documentation for any use of the term "array" or "arrays" and couldn't find anything. 

I think that some links in the docs to Stackblitz examples would be very helpful. Without actual working examples, documentation alone usually leaves out some small essential piece that it assumes the reader already knows about.

Thanks again.

**Comment by nartc** [comment]
@johnpankowicz You shouldn't run into any limitations (that cannot be adjusted/fixed) with POJOs instead of Classes. Of course, feel free to open issues and report anything at all that you run into.

>Also is there a way to use Classes and not manually decorate the members?

The previous iteration of this AutoMapper (`@nartc/automapper`), I had a `automapper-transformer-plugin` that can be utilized to also **auto-decorate** the members but I don't have one yet in this new iteration (`@automapper/*`). I do plan to add the plugin back to `classes` package though. Track it here #261

**Comment by nartc** [comment]
3.0.5 has been released with the transformer plugin. https://github.com/nartc/mapper/releases/tag/3.0.5
