### ISSUE TITLE
Can I create metadata in pojos that can auto map blackbox object type?

### ISSUE THREAD

**Issue by MrVarens** [nartc/mapper#260]
Just want to ask if there is way to automatically copy whole object without creating another metadata for it?

I know that i can do that with use of `map.forMember(x => x.obj, mapFrom(x => x.obj))`, but want to know if I can do that only with use of `createMetadataMap()`?

Example:
```
interface Src {
    number: number;
    obj: object; // Any blackbox object (have no idea what will be inside of it) that i want to have inside destination object
}

interface Dest {
    number: number;
    obj: object;
}

createMetadataMap<Src>('Src', {
    number: Number,
    obj: Object
});

createMetadataMap<Dest>('Dest', {
    number: Number,
    obj: Object
});

const mapper = createMapper({
    name: 'AutoMapper',
    pluginInitializer: pojos,
    namingConventions: new CamelCaseNamingConvention()
});
mapper.createMap<Src, Dest>('Src', 'Dest');
const result = mapper.map<Src, Dest>({number: 123, obj: {test: 321}, anotherValue: 'test'}, 'Dest', 'Src');
```

Expectation:
`result` should be `{number: 123, obj: {test: 321}}`

**Comment by nartc** [comment]
Thanks for opening the issue.

You mean like an arbitrary object (`Record<string, any>`?) No, not at the moment. Since AutoMapper really depends on convention which dynamic object does not really apply. That is tricky because at runtime, AutoMapper checks for if a value is an object to determine whether or not it should start mapping some nested Mapping. In the case of arbitrary objects, `core` would get more complex with more conditional checks. Unless there are strong reasons why you would need to map arbitrary objects (like primitives) rather than just a little bit convenience, I don’t think I’ll add this. `forMember` is the correct way of achieving that.

**Comment by MrVarens** [comment]
I am asking because it could be great to limit configuration to minimum, huge adventage of .NET AutoMapper is that for simple mapping you almost don't have to configure anything, but I understand that javascript have limitation in that subject.

Thanks for fast answer!

**Comment by nartc** [comment]
@MrVarens Totally. I am all for ease of usage but yes as you noticed, this is TypeScript limitation because TypeScript's reflection isn't as good as C#'s. Although I don't have plan to support this but I might in the future. So I'd suggest to stick with `forMember` for now. Sorry for the inconvenience.

**Comment by nartc** [comment]
@MrVarens I went ahead and gave this one a try in 3.0.5. Read through the Release Notes to see how it works. https://github.com/nartc/mapper/releases/tag/3.0.5
