### ISSUE TITLE
[classes] What if the constructor of our source class has parameters?

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#265]
Hey!

I'm trying to model something like this:

```typescript
class A {
   @AutoMap()
   foo: number
   bar: string
	constructor(param: string) { this.bar = param.toLowerCase() }
}
class AVm { // this won't use `bar`. it doens't even need to know that this prop exists
   @AutoMap()
   foo: number
}

// ...
mapper.createMap(A, AVm)

// ...
// ❌ throws an UnhandledPromiseRejectionWarning
mapper.map(new A('foo'), Avm, A)
/*
at Object.instantiate (x/packages/classes/src/lib/utils/instantiate.util.ts:30:21)
at preMap (x/packages/classes/src/lib/classes.ts:135:32)
at originalClasses.preMap (x/src/common/lib/automapper/custom-classes.plugin.ts:33:34)
at Object.map (x/packages/core/src/lib/create-mapper/create-mapper.ts:63:32)
*/
```

Line 30 below triggers the error (`TypeError: Cannot read property 'toLowerCase' of undefined` in my case)
https://github.com/nartc/mapper/blob/23174a13d5a2d17cf78b1ffa81a102b31cd7d25c/packages/classes/src/lib/utils/instantiate.util.ts#L28-L30

My questions are:

1. Is this a known limitation? _(if so, I think it should be on doc's limitations page)_  
2. Are you planning to support this somehow? _(idk how to fix this nicely at lib-level)_

**Comment by nartc** [comment]
This is definitely a language limitation. In .NET, the consumers can actually provide different constructors as a configuration because there is overload in C#. In JavaScript, a class can only have 1 constructor. In addition, all classes have an implicit Default Constructor function and all functions have an implicit `arguments` array which is pretty impossible to detect at runtime that a Class has a Custom Constructor with some parameters. 

Please feel free to open a PR in the docs for this. I didn't include this as a limitation to AutoMapper because it is  more like "known fact" in the JavaScript ecosystem.

The best way to solve this issue is have `A` to have some static function:

```ts
class A {
   @AutoMap()
   foo: number
   bar: string
   
   // this way, the "custom" instantiation logic is still encapsulated in the class itself.
   static withBar(param: string) {
      const a = new A();
      a.bar = param.toLowerCase();
      return a;
   }
}

// later
const newA = A.withBar('foo');
mapper.map(newA, AVm, A);
```

**Comment by micalevisk** [comment]
Oh right, ty!

I was thinking more like **"if I'm _just_ creating an instance of `AVm` when doing `mapper.map(newA, AVm, A)` the mapper shouldn't need to create an instance of `A`"**, but I was wrong xD
