### ISSUE TITLE
Mapping of undefined values

### ISSUE THREAD

**Issue by MrVarens** [nartc/mapper#273]
Is there a way to skip variables that are `undefined` from output object?

Iterating over output variables and removing them is one way but its can be expensive, would be nice if mapper could skip them during mapping.

### Example

Source mapping:
`
{
    param1: String,
    param2: String
}
`

Destination mapping:
`
{
    param1: String,
    param2: String
}
`

Source object:
`
{
    param1: 'value'
}
`

Output:
`
{
    param1: 'value'
    param2: undefined
}
`

Expected output:
`
{
    param1: 'value'
}
`

**Comment by nartc** [comment]
Hi @MrVarens , thanks for opening the issue. May I ask what the ultimate goal for this is? In other words, how do `undefined` fields affect your use-case? From my perspective, I didn't trip `undefined` to keep the shape of the models intact after mapping. Also since I built AutoMapper with "transferring object over network (aka backend -> frontend)" in mind which will strip `undefined` values by default (serialization).

**Comment by MrVarens** [comment]
Sorry for late answer. My problem is that i refactor application to use dto-s, this projecrt is pretty big and till now all objects had only variables with values. After refactoring to use auto mapper I had to fix all of my unit tests because there are object with have only couple of values but interface contains dozen of them.

ex.

Pre auto mapper add:
Test expect (and receives) object with 10 parameters (that contains values)

After using auto mapper:
Test receives 30 parameters, 20 of them have value of undefined.

**Comment by nartc** [comment]
Would `JSON.parse(JSON.stringify(obj))` help in this case?

**Comment by MrVarens** [comment]
Unfortunately no, because Dates will be then casted to string.

What I did for now is separate instance of mapper for unit tests that extends my mapper class used by application. This extended class after mapping have additional logic that each by all of parameters and remove that one with are undefined, but still would be great if it could be done by default in auto mapper.

**Comment by nartc** [comment]
Sorry for the inconvenience. That’s one of the reasons for this rework AutoMapper. Before, AutoMapper dictates Empty Values; I could make it all undefined, or all null, or stripped because that was one of the options. But I’ve got quite a few different requests on keeping undefined as undefined, null as null, and various other use-cases. Hence, I reworked AutoMapper in a way that it won’t dictate how empty values will be mapped anymore.

However in your case, it’s a little different. It can be baked into AutoMapper for sure but then I am a little hesitant because of mentioned reasons. You can do something like this: https://automapperts.netlify.app/docs/plugins-system/extend-plugin instead of extending the Mapper. Now, I also expose “instantiate” which is the main culprit of “undefined” values so you might want to explore how you want to override that instead of overriding “preMap” like shown in the docs.

**Comment by MrVarens** [comment]
I saw that extending plugin but from what I understend its called before mapping, while its good for maping null to undefined it wont help when i want to remove variable completly from output. Variables in output base on metadata and because this plugin functions are called before mapping I cant manipulate output object.

I do not uderstand what you mean by "expose instantiate", can you give me some more details about it?

**Comment by nartc** [comment]
Right right, I see what you're saying now. Assume that I won't be baking "stripping undefined" into AutoMapper, you're left with two approaches:
- Use `afterMap()`. This won't affect any functionalities of AutoMapper but there is no **Global** AfterMap which means you'd need to re-attach `afterMap()` for each Mapping

```ts
export function someAfterMapFnName(source, destination) {
   // logic to strip undefined off of destination
}

mapper.createMap(Foo, Bar)
   .afterMap(someAfterMapFnName);
   
mapper.createMap(AnotherFoo, AnotherBar)
   .afterMap(someAfterMapFnName);
```

- Create a custom plugin (by "Extending" it using the docs above) and attach a `postMap()` to the plugin (here's an example from the `@automapper/sequelize` plugin: https://github.com/nartc/mapper/blob/main/packages/sequelize/src/lib/sequelize.ts). `postMap()` receives `destination` (which is the model itself) and `destinationObj` which is the mapped object. `postMap()` **needs** to return some value.

Personally, I think `postMap()` will achieve what you need.

To answer the question about `instantiate`, if you take a look [here](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/classes.ts#L32), you'll see that `instantiate` is now a part of the `plugin` which allows it to be override-able. `instantiate` is a function that runs over the Model to instantiate it (instead of `new Model()`) to attach the metadata so that at the time of mapping, AutoMapper can iterate through the available properties on the Model. 

```ts
class Foo {
   @AutoMap();
   foo: string;
}

new Foo(); // Foo {} "foo" is not known
instantiate(Foo); // Foo { foo: undefined } "foo" is known and iterable.
```

**Comment by MrVarens** [comment]
Yea that `postMap` is good for me, I didnt saw it in my local code, probably this is some new feature, right?

Thanks for really fast help!

**Comment by nartc** [comment]
No problem! I'm glad I was able to help. `postMap` was added in 3.2.0 https://github.com/nartc/mapper/blob/main/CHANGELOG.md#320-2021-03-06 

Can we close this issue?

**Comment by MrVarens** [comment]
Only thing that can be considered is adding a way to removing variables without value during mapping by setting some config variable, because it could be less complex then removing this variables after mapping. But I understand that for reasons mentioned before you may not want to implement it.

For me I have a way to fix my problem, its not super important to make unit tests with the best performance so `postMap` will be ok for this case thats why I will leave decision for you about stripping undefined vars. As for now we can close this issue.
