### ISSUE TITLE
[Bug] Automap not work as expected when using mikro-orm entities

### ISSUE THREAD

**Issue by notmedia** [nartc/mapper#311]
Hi! I created a repo to reproduce the bug: https://github.com/notmedia/automapper-mikroorm

For example, I have a `User` entity in `user/user.entity`:

```ts
@Entity({ tableName: 'users' })
export class User {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  @AutoMap()
  uuid!: string;

  @Property()
  //@AutoMap()
  name!: string;
}
```

And the `UserView` in `user/user.view.ts`:

```ts
@ObjectType()
export class UserView {
  @Field()
  @AutoMap()
  uuid: string;

  @Field()
  @AutoMap()
  name: string;
}
```

I expect that if automap decorator is not defined for both sides (entity and view) on prop I should get an object without this prop - this works.

I expect that if automap decorator is not defined on prop on entity side, I should get an error, that automap couldn't be done. But I am getting object with this prop after mapping:

```bash
users:  [ User { uuid: '753fb706-79c0-4684-b71b-c06035c21b20', name: 'test' } ]
mapped:  [
  UserView {
    uuid: '753fb706-79c0-4684-b71b-c06035c21b20',
    name: 'test'
  }
]
```

You can see, I commented in  `user/user.entity` automap decorator for `name`, but getting this name after mapping.

Also, If I comment the automap on `uuid` prop on entity side, that marked with decorator PrimaryKey it works as expected:

```bash
users:  [ User { uuid: '753fb706-79c0-4684-b71b-c06035c21b20', name: 'test' } ]
[Nest] 88746   - 01/07/2021, 20:17:26   [AutomapperModule] 
Unmapped properties:
-------------------
uuid
 +2869ms
mapped:  [ UserView { uuid: undefined, name: 'test' } ]
```

I can't understand why it's happening. Maybe there are conflicts in reflect metadata.

**Comment by nartc** [comment]
Can you do me a favor and try replacing `name` with a different key like `fullName` or `userName` and see if the behavior still persists?

**Comment by notmedia** [comment]
When I changed to:
```ts
  @Property({ fieldName: 'name' })
  fullName!: string;
```

it works

But in another project, that unfortunately I can't share it doesn't. If you have any ideas, can you explain what's going on?

**Comment by notmedia** [comment]
Some updates: with nest watch enabled on my another project build not updated correctly (I don't know why, but it's another story)

And now I think I found the problem (updated the repo to reproduce)

In my Entity class I also have a constructor

```ts
@Entity({ tableName: 'users' })
export class User {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  @AutoMap()
  uuid!: string;

  @Property()
  @AutoMap()
  name!: string;

  @Property()
  @AutoMap()
  password!: string;

  constructor(name: string, password: string) {
    this.name = name;
    this.password = password;
  }
}
```

If I comment automap on prop `password` the mapping error didn't occurs, and I am getting the object with `password` field - this is a bug

If I comment `this.password = password` in constructor, then it works as expected

**Comment by nartc** [comment]
Might still be an actual bug (or more like weird behavior) but I'll try my best to explain.

The purpose of `AutoMap` is to save the metadata of a certain property on a class. Why? In TypeScript, when you have the following class:

```ts
class User {
   firstName: string;
   lastName: string;
}
```

Doing `new User()` yields `User {}` without any information about its properties (`firstName` and `lastName` in this case). Without decorators, you can adjust your code a little bit:

```ts
class User {
   firstName: string;
   lastName: string;

   constructor(firstName: string, lastName: string) {
      this.firstName = firstName;
      this.lastName = lastName;
   } 
}
```

Now if you do `new User()`, without passing anything in, you'll get `User { firstName: undefined, lastName: undefined }`. Now `firstName` and `lastName` are **visible** on the class. Alternatively, you can have the shorthand syntax like:

```ts
class User {
   constructor(public firstName: string, public lastName: string) {} 
}
```

This is equivalent to the 2nd snippet. However, you might know all of these already. Back to `@AutoMap()`, `AutoMap` stores the metadata that is: "class `User` has `firstName` and `lastName` property" in a collection. So when `createMap()` is called, an internal implementation of `instantiate(User)` (like a better version of `new User()`) will be able to apply the metadata that `AutoMap` saves to the `User` so that **AutoMapper** has `User { firstName: undefined, lastName: undefined }` to construct the **auto-configurations**.

Back to your question, since you explicitly assign the properties in the `constructor`, technically, `AutoMap` is redundant. But there might be some weird behaviors going on here. I'll investigate further when I have some free time (there's a release going on at work so I'm pretty swamped atm).

Let me know if my explanation makes sense or not. Thank you for reporting.

**Comment by notmedia** [comment]
Yep, I understood this, thank you for explanation.

Would be grate if we can investigate it and fix it.

**Comment by nartc** [comment]
@notmedia I've taken a look at the repo and it is really just how JavaScript works really. Since you have those in the constructor, it is really ok to drop `AutoMap`. I cannot **not map** `name` and `password` because they're explicitly assigned in the constructor. I am closing this. Feel free to open a new issue if you run into things that you think is not working properly.
![image](https://user-images.githubusercontent.com/25516557/124322241-b83a0000-db44-11eb-8a0c-2ac6f3419766.png)
