### ISSUE TITLE
Mapping properties with different names and types

### ISSUE THREAD

**Issue by HurricaneDancer** [nartc/mapper#322]
I have an entity called Character, and a CharacterDTO. The Character entity has a property called character_skill which is an array of skills that the character has. The dto property is called "skills". However, using the @AutoMapper() decorator on those properties does not help, and mapFrom when creating a mapper using forMember throws a type error. 

Either this is a bug, or I am doing something wrong. I dont really want to have my database using the same standards as the DTOs. The database uses snake case and singular names, while the DTOs use camel case and plural names (character_skill vs skills).

**Comment by nartc** [comment]
Hi @HurricaneDancer , thank you for reporting. Can you share your models and the mapping config you currently have? You mentioned a type error with `forMember()`, what's the error?

**Comment by HurricaneDancer** [comment]
This is the [codesandbox](https://codesandbox.io/s/priceless-mahavira-ttwlm?file=/src/index.ts:1121-1142)

**Comment by nartc** [comment]
Thank you. I'm going to copy the models here to continue the discussion

```ts
class SkillEntityTest {
  @AutoMap()
  value: number;
}

class SkillDTOTest {
  @AutoMap()
  value: number;
}

class CharacterEntityTest {
  @AutoMap()
  id: string;

  @AutoMap()
  name: string;

  @AutoMap({ typeFn: () => SkillEntityTest }) // I added this
  character_skill: SkillEntityTest;
}

class CharacterDTOTest {
  @AutoMap()
  id: string;

  @AutoMap()
  name: string;

  @AutoMap({ typeFn: () => SkillDTOTest }) // I added this
  skills: SkillDTOTest;
}
```

and your profile

```ts
const testMapperProfile: MappingProfile = (mapper: Mapper) => {
  mapper.createMap(SkillEntityTest, SkillDTOTest);
  mapper.createMap(CharacterEntityTest, CharacterDTOTest).forMember(
    (d) => d.skills,
    mapWith(
      () => SkillDTOTest,
      (s) => s.character_skill,
      () => SkillEntityTest
    )
  );
};
```

There are a couple of problems that you run into:
1. You didn't create a mapping for `SkillEntityTest, SkillDTOTest`.
2. `character_skill` and `skills` do not really share anything in common in terms of property name. I mean, AutoMapper cannot deduce that `skills` will be mapped from `character_skill`. Which means, we need to use `forMember` for it. To map a nested model with `forMember()`, `mapWith()` is the map function to use.

There are cases you might want to use `mapFrom()` if your nested model is simple enough. So instead of the `mapWith()` example I provided, you could do: 

```ts
mapper.createMap(CharacterEntityTest, CharacterDTOTest)
   .forMember(d => d.skills, mapFrom(s => {
      const skills = new SkillDTOTest();
      skills.value = s.character_skill.value;
      return skills;
   }))
```

Another alternative here is that you rename `CharacterDTOTest#skills` to `characterSkill` (camelCase version of `character_skill`) and `AutoMap` can do its job. Now the profile can become:

```ts
const testMapperProfile: MappingProfile = (mapper: Mapper) => {
  mapper.createMap(SkillEntityTest, SkillDTOTest);
  mapper.createMap(CharacterEntityTest, CharacterDTOTest);
};
```
But you'd need to provide the `typeFn` for `character_skill` and `characterSkill`. Does this answer your question?

**Comment by HurricaneDancer** [comment]
it definitely does, thank you!

**Comment by nartc** [comment]
Great. Lemme know if you have any questions. Otherwise, can we close this issue?

**Comment by HurricaneDancer** [comment]
All good for now :)
