### ISSUE TITLE
Flatten model without named prefix.

### ISSUE THREAD

**Issue by turbosheep44** [nartc/mapper#335]
## Problem

I would like to be able to flatten a model without the need for the destination model to have every attribute prefixed.

## Example 

Lets assume I have the following entities:
```ts
class Item {
    name: string
    price: number
}

class CartItem {
    item: Item
    quantity: number
}
```

And I want to map a `CartItem` to the following DTO:

```ts
class CartItemDto {
    name: string
    price: number
    quantity: number
}
```

As far as i can tell, there is no way to do this at the moment. The only option is to call the fields in `CartItemDto` `itemName` and `itemPrice`, but that's verbose and also quite restrictive.

## Proposed Solution

Looking through the docs, I thought that `mapWith` would provide the solution here:

```ts
        mapper.createMap(CartItem, CartItemDto)
            .forMember(
                dst => dst,
                mapWith(CartItemDto, Item, src => src.item)
            )
```

Unfortunately, this ends up producing an object like this:

```json
{
    "quantity": 2,
    "": {
         "name": "Apple",
         "price": 100
    }
}
```

I think it would make more sense if providing the `Selector` `dst => dst` to `forMember`  maps directly to the parent object rather than to a property named `""`.

**Comment by nartc** [comment]
Hi @turbosheep44, 

First of all, thank you for opening the issue. Much appreciated. 

Secondly, I do understand where you're coming from but I think what you're proposing will add unnecessary complexity to the library. And it might be _weird_ to use. Let me explain

```ts
class Item {
    name: string
    price: number
}

class CartItem {
    item: Item
    quantity: number
}

class CartItemDto {
    name: string
    price: number
    quantity: number
}
```

Assuming there's already a feature in AutoMapper to do what you're proposing, all is well with your initial models

```ts
mapper.createMap(CartItem, CartItemDto)
   .forMember(d => d, mapWith(CardItemDto, Item, src => src.item))
```

However, this is implicitly restricting consumers in a way that `Item` is hard to change/modify

```ts 
class Item {
    name: string
    price: number
    newProperty: string; // <-- every new property added here needs to be added to CartItemDto as well
}

class CartItemDto {
    name: string
    price: number
    newProperty: string; // <-- this might keep getting longer and longer
    quantity: number
}
``` 

Now assuming that `newProperty` is not needed in `CartItemDto` at all, the end result of `cartItemDto` will still contain a value for `newProperty` and that is wrong if looking from the models' perspective.

In my opinion for this case, using `forMember` explicitly is a better solution overall

```ts
mapper.createMap(CartItem, CartItemDto)
   .forMember(d => d.name, mapFrom(s => s.item.name))
   .forMember(d => d.price, mapFrom(s => s.item.price))
```

Any developers will be able to figure out what's going on just by looking at the mapping configuration rather than guessing what might end up in the end result. 

Of course, I'm welcoming any constructive argument. What do you think?

**Comment by turbosheep44** [comment]
Hi @nartc,

You actually described my real world use case quite aptly. The `Item` does have fields which I don't want in the DTO.

```ts
class Item {
    @AutoMap() name: string
    @AutoMap() price: number
    @AutoMap() stock: number;
}

class CartItem {
    @AutoMap() item: Item
    @AutoMap() quantity: number
}

class CartItemDto {
    @AutoMap() name: string
    @AutoMap() price: number
    @AutoMap() quantity: number
    // no need to add stock here
}
```

Then, when I call the mapper to perform the mapping, I expect it to *create a `CartItemDTO` from the given `CartItem`*. If the `CartItem` has extra fields which don't have a place to go in `CartItemDTO`, that's fine. 

In fact, the mapper doesn't give an error or a warning when used like this, which is exactly what I would expect.

The other option, using `mapFrom` explicitly for each field, just seems like too much boilerplate for a library which is designed to reduce boilerplate. Granted, the boilerplate is not repeated every time I want to use the mapping but still for a large object this can be quite tedious.

As for developer readability, I think that using `mapWith` as below says to me *fill the destination element with fields from `src.item`*. 

```ts
mapper.createMap(CartItem, CartItemDto)
   .forMember(d => d, mapWith(CardItemDto, Item, src => src.item))
```

Just as the use case from the docs reads *fill `dst.someProfile` with fields from `src.originalProfile`*.

```ts
mapper.createMap(User, UserDto).forMember(
  (dst) => dst.someProfile,
  mapWith(ProfileDto, Profile, (source) => source.originalProfile)
);
```

**Comment by nartc** [comment]
@turbosheep44 ,

I understand the verbosity and boilerplatey of using `forMember` explicitly. When I worked on a .NET project in the past, I saw a lot of boilerplate from Mapping Configuration as well, and I think that it is by design.

Now on to `mapWith`, the idea of `mapWith` is: "_for this **property** on the destination, please use these models and that **property** on the source to map it with_". So the following usage does not really make sense to me at first glance:

```ts
mapper.createMap(CartItem, CartItemDto)
   .forMember(d => d, mapWith(CardItemDto, Item, src => src.item))
```

Back to your request, we might want to add a new method to achieve that instead of reusing `forMember` (again, `forMember` already does not make sense to _fill_). I am thinking of `mergeWith()` or `mergeFrom`

```ts
mapper.createMap(CartItem, CartItemDto)
   .mergeWith(Item, src => src.item);

mapper.createMap(CartItem, CartItemDto)
   .mergeFrom(Item, src => src.item);
```

We also have to think about the order of executions if the consumers do the following:

```ts
// Item has { name, price }
mapper.createMap(CartItem, CartItemDto)
   .forMember(d => d.name, fromValue('some name before fill???'))
   .mergeWith(Item, src => src.item) // this should fill {name, price} from Item
   .forMember(d => d.name, ignore());
```

What would happen to `d.name` in this case?

**Comment by turbosheep44** [comment]
@nartc 

Although the .NET boilerplate for mapping configuration may be intentional, personally I have always found that less boilerplate it better. I guess that's the reason I am not a fan of explicitly using `forMember` for every element. :stuck_out_tongue: 

I agree with you that mapping multiple members with a call to `forMember` does cause a problem for readability and I think a new method would be better. 

From the two options you proposed I prefer `mergeWith` as it reads like "*map from `CartItem` to `CartItemDto` and then merge the result with a mapping from `Item` (found at `src.item`) to `CartItemDto`*".

```ts
mapper.createMap(CartItem, CartItemDto)
   .mergeWith(Item, src => src.item);
```

However, how about `forParent` or `forSelf`, I think that this matches the existing `forMember` syntax a little better. It would read "*for properties on the parent, map from `src.item` (of type `Item`)*".

```ts
mapper.createMap(CartItem, CartItemDto)
   .forParent(Item, src => src.item);
```
 
A complete example:

```ts
    /* map from CartItem to CartItemDto,
           for `dst.other_property`        map to `"hello"`
           for `dst.name`                  map using `NameConverter`
           for properties on the parent    map from `src.item` (of type `Item`) */
    mapper.createMap(CartItem, CartItemDto)
        .forMember(dst => dst.other_property, fromValue("hello"))
        .forMember(dst => dst.name, convertUsing(fullNameConverter))
        .forParent(Item, src => src.item)
```

As for order of operations, I am unsure how the library current handles this case but I see no reason why `mergeWith`/`forParent` should be any different.

```ts
mapper.createMap(CartItem, CartItemDto)
   .forMember(d => d.name, fromValue('name_x'))
   .forParent(Item, src => src.item) // fills {name, price} from Item
   .forMember(d => d.name, ignore());
```

Assuming `forMember` calls are currently handled in the order that they are called, I would expect that the `name` property is `undefined` in the above snippet.

**Comment by nartc** [comment]
@turbosheep44 I like `forParent`, great suggestion. Thank you. I guess it's time to start planning for this feature :)

**Comment by turbosheep44** [comment]
@nartc  I just got around to using this on my own project and I've found some unexpected behavior. I've opened #340 showcasing this problem. :smile:
