### ISSUE TITLE
Please document ts/node version requirements

### ISSUE THREAD

**Issue by ex-nerd** [nartc/mapper#426]
### Is your feature request related to a problem? Please describe.

Many companies are still stuck using Typescript 3.9, but `AutoMapper` does not compile properly when using this older version of typescript.  Errors include things like:

- `node_modules/@automapper/core/src/lib/types/core.d.ts:149:24 - error TS1005: ',' expected.`
- `node_modules/@automapper/core/src/lib/types/core.d.ts:150:7 - error TS1011: An element access expression should take an argument.`
- `node_modules/@automapper/core/src/lib/types/core.d.ts:151:1 - error TS1109: Expression expected.`

### Describe the solution you'd like

These compile errors go away with `v4.1.x`, so it seems this is an issue with the typescript version rather than a problem with `AutoMapper` itself.  It would be nice to put minimum version requirements somewhere in the docs, if not in the `package.json` file itself.

**Comment by micalevisk** [comment]
I guess this requirement list could leave under https://automapperts.netlify.app/docs/getting-started/installation

**Comment by nartc** [comment]
Hi @ex-nerd , sorry for being late on getting back on this. The main issue is that I use `Labeled Tuple Elements` (https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#labeled-tuple-elements) and it's available only since TS 4.0

I add `skipLibCheck` as a recommended `tsconfig` in [Installation docs](https://automapperts.netlify.app/docs/getting-started/installation).
