### ISSUE TITLE
Issues using `@AutoMap` with mikro-orm references

### ISSUE THREAD

**Issue by calvinwyoung** [nartc/mapper#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm trying to use `@AutoMap` with mikro-orm. This worked fine in v7, but I haven't been able to get it working in v8.

Here's a repo that that demonstrates the issue:
https://github.com/calvinwyoung/auto-mapper-mikro-orm-sample

This is built on the same repo used in #387.

### Models/DTOs/VMs

https://github.com/calvinwyoung/auto-mapper-mikro-orm-sample/blob/main/src/models.ts

### Mapping configuration

https://github.com/calvinwyoung/auto-mapper-mikro-orm-sample/blob/main/src/query.ts#L24-L25

### Steps to reproduce

https://github.com/calvinwyoung/auto-mapper-mikro-orm-sample

### Expected behavior

I'd expect the `query.ts` script to print the following:

```ts
{
  id: 1234
  name: "Author Name",
  bookId: 123
}
```

Unfortunately I keep getting this error:

```ts
Author {
  id: 1234,
  name: 'Author Name',
  book: Reference { entity: Ref<Book> { id: 123, author: [Reference] } }
}
Error: Reference<Book> 123 not initialized
    at Reference.getEntity (/Users/calvin/Code/auto-mapper-mikro-orm-sample/node_modules/@mikro-orm/core/entity/Reference.js:85:19)
    at serializeEntity (/Users/calvin/Code/auto-mapper-mikro-orm-sample/node_modules/@automapper/mikro/index.cjs:27:79)
    at Object.mergedOptions.preMap (/Users/calvin/Code/auto-mapper-mikro-orm-sample/node_modules/@automapper/mikro/index.cjs:44:38)
    at Proxy.<anonymous> (/Users/calvin/Code/auto-mapper-mikro-orm-sample/node_modules/@automapper/core/index.cjs:539:35)
    at /Users/calvin/Code/auto-mapper-mikro-orm-sample/src/query.ts:31:24
    at Generator.next (<anonymous>)
    at fulfilled (/Users/calvin/Code/auto-mapper-mikro-orm-sample/src/query.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Minimum reproduction code

https://github.com/calvinwyoung/auto-mapper-mikro-orm-sample

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [X] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### Other package and its version

mikro-orm v5.1.1

### AutoMapper version

8.1.0

**Comment by nartc** [comment]
Hi @calvinwyoung, thanks for reporting.

I would like to explain more about your specific issue.

First, you **NEED** to populate/initialize your `Reference` for AutoMapper to work correctly (regardless of v7 or v8).

If you **DO NOT** populate the `'book'` reference, you'd get the:
- `Not Initialized` error in v8
- An undefined `bookId` in v7
<img width="684" alt="image" src="https://user-images.githubusercontent.com/25516557/162119256-bc27543d-4f6e-43e2-bb84-683d96cb6482.png">

If you populate the `'book'` reference, you'd get:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/25516557/162119232-2359403c-c5f8-43c7-b324-bf4e183f8c25.png">
- Infinity loop (*) in v8 (8.1.0)
- A correct DTO in v7
<img width="677" alt="image" src="https://user-images.githubusercontent.com/25516557/162119400-d0bcd7b2-90e2-4e01-81a7-309fc2387819.png">

This is because in v7, the `Reference` is serialized into a plain object and return early without recursively serializing nested reference (e.g: `Author <-> Book`, v7 stops at `author.book` and won't go `author.book.author`). With this in mind, if you add another _flatten_ property to `AuthorDto` like `bookAuthorName` (expected to be mapped from `book.author.name`)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/25516557/162119552-3c77e311-6439-4016-bafb-25b5a2e9a234.png">

v7 will fail to map this (`bookAuthorName` will be undefined)
<img width="884" alt="image" src="https://user-images.githubusercontent.com/25516557/162119614-ac92b09e-4fc5-4fc3-80e6-2d981a561b9b.png">

Back to v8, I've released 8.2.1 to fix the infinity loop issue with `mikro()` **as well as** supporting for deep reference. So the `AuthorDto#bookAuthorName` will be flatten and mapped correctly in 8.2.1
<img width="674" alt="image" src="https://user-images.githubusercontent.com/25516557/162119776-98c0d57a-7ae6-42b6-8195-0be2f55fa72d.png">
