### ISSUE TITLE
[v8] Mapping of custom type not working

### ISSUE THREAD

**Issue by PieterBoeren** [nartc/mapper#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I have a custom object which I map with a "convertUsing" to a specific type, this was working perfectly in v7, but now I migrated to v8, the mapping doesn't work anymore.

I'm using the transformer plugin and have no @AutoMap() decorators in my code.

When debugging I get this:

![image](https://user-images.githubusercontent.com/43775697/163997772-56d04506-7e7c-4aca-9367-872979b44cab.png)

The "type" is undefined, resulting in a runtime error on the "isDateConstructor" function (called from the "getMetadataList" function:

![image](https://user-images.githubusercontent.com/43775697/163998408-401df811-27a7-4ee2-b601-f63aef169ae9.png)

### Models/DTOs/VMs

VM:

```TS
class BuildingDifferenceViewModel {
  // Removed all other properties for clarity
  public geometrieVerschil?: Proj4GeoJSONFeature;    
}
```

DTO:

```TS
class BuildingDifferenceDto {
 
  public geometrieVerschil?: GeoJSON & { crs?: { type: string; properties: { name: string } } };
}```

### Mapping configuration

```TS
createMap(
    mapper,
    BuildingDifferenceDto,
    BuildingDifferenceViewModel,
    forMember(
      (destination) => destination.geometrieVerschil,
      convertUsing(geoJson2Proj4GeoJsonFeatureConverter, (source) => source.geometrieVerschil)
    ),
```

### Expected behavior

Custom types to be handled without errors

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.3.2

**Comment by micalevisk** [comment]
I guess you need to share that `geoJson2Proj4GeoJsonFeatureConverter`?

A repository reproducing your issue would be great

**Comment by PieterBoeren** [comment]
Reproduction repository is [here](https://github.com/PieterBoeren/cra-automapper).

- yarn install
- yarn start
- Open the developer console in the browser, the error is there.

**Comment by nartc** [comment]
@PieterBoeren sorry for the late response. The transformer plugin isn't smart enough (probably a missing feature or a limitation) to determine that the type reference is not a callable constructor, hence result in the `type()` returning `undefined`. What I would suggest to do is to add `@autoMapIgnore` to `someGeometry` fields so that it is ignored by the transformer plugin.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/25516557/166831379-0ae1b38f-65bd-4ed0-9751-dc50ed003154.png">

PS: Another bug I guess in your code is you probably want to map from the `DTO` to the `ViewModel` here as it is that order in your `createMap(mapper, DTO, ViewModel)`
<img width="865" alt="image" src="https://user-images.githubusercontent.com/25516557/166831431-b73a19af-c032-4d6a-9a00-d0d1cbc9951a.png">

**Comment by PieterBoeren** [comment]
Thanks, that fixed it :)
