### ISSUE TITLE
[docs] Wrong hyperlink to `NamingConvention` page

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#476]
### Is your feature request related to a problem? Please describe.

1. https://automapperts.netlify.app/docs/fundamentals/auto-flattening
2. click on `NamingConvetion` (ie., https://automapperts.netlify.app/docs/fundamentals/auto-flattening/naming-convention)

### Describe the solution you'd like

N/A

btw I feel that we need an issue form for documentation-related changes

### Describe alternatives you've considered

I didn't understood how to fix that on https://github.com/nartc/mapper/blob/031db42ddc647506d5b568edc6e658f15b5ced65/packages/documentations/docs/fundamentals/auto-flattening.mdx because there is an `naming-convetion.mdx` but the hyperlink shoud be  
https://automapperts.netlify.app/docs/mapping-configuration/naming-conventions

**Comment by nartc** [comment]
Thanks for reporting. This issue seems weird and might be related to Docusaurus instead. The issue only surfaces if you refresh the page (https://automapperts.netlify.app/docs/fundamentals/auto-flattening). After you navigate within the documentation then the hyperlink works as expected. This seems to happen for all pages. I'll investigate further
