### ISSUE TITLE
Support for transforming plain objects to classes

### ISSUE THREAD

**Issue by gpa** [nartc/mapper#88]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior

I'm trying to convert a plain object, coming from a web request, to a dto.
Basically I'm trying to avoid class-transformer and I've written the following transform pipe for nestJs:
```
@Injectable()
export class DtoPipe implements PipeTransform {
    @InjectMapper()
    private automapper: AutoMapper;
    public transform(value: any, metadata: ArgumentMetadata) {
        return this.automapper.map(value, metadata.metatype, metadata.metatype);
  }
}
```
To make this work I had to add the mapping:
```
     mapper.createMap(RegisterUserDto, RegisterUserDto);
```
for each of my dtos. It works but feels like a hack. I wish there was a more intuitive way with options like forbidUnknownValues.

## Expected behavior

Introduce some of class-transformer features to this library or let me know if there is another way to do this

## What is the motivation / use case for changing the behavior?
Avoiding class-transformer dependency since this library already satisfies most of the typical requirements.

**Comment by nartc** [comment]
Hi @gpa , thanks for opening the issue. Providing this feature should be easy because internally, AutoMapper needs to do something like this already. All I have to do is to expose this function https://github.com/nartc/mapper/blob/master/src/metadata-explorer.ts#L111 to the public API. 

However, let's take a look at your specific use-case. Why do you need to transform the incoming request to a DTO? What are you going to use that "transformed" DTO afterwards?

**Comment by gpa** [comment]
hi @nartc, thanks for quick reply.
```
@Controller('/users')
export class UserController {
  constructor(private readonly userService: UserService) {}
  @Post()
   public async create(@Body() registerUserDto: RegisterUserDto, @Res() res: Response) {
       const createdUser = await this.userService.register(registerUserDto);
       res.status(HttpStatus.CREATED).location(`/users/${createdUser.id}`).json(createdUser).send();
  }
}
```
```
@Injectable()
export class UserService {
    @InjectRepository(UserEntity)
    private userRepository: Repository<UserEntity>;
    @InjectMapper()
    private mapper: AutoMapper;

    public async register(registerUserDto: RegisterUserDto): Promise<UserDto> {
        const user = this.mapper.map(registerUserDto, UserEntity);
        await validateOrReject(user);
        await this.userRepository.save(user);
        return this.mapper.map(user, UserDto);
    }
```
Even though I marked the request param `@Body() registerUserDto: RegisterUserDto` as dto, NestJs will pass a plain object unless I install class-transformer, so that the mapping to entity will fail. Many other frameworks will pass plain objects as well. I guess passing dtos to services is less common but the use-case is really the transforming of received data for further processing. That's why an option like forbidUnknownValues would be important so that values won't be ignored.
Let me know what you think

**Comment by nartc** [comment]
Thanks for providing the information. With your use-case, I believe you can just provide extra information to `this.mapper.map()` so AutoMapper has more information about your DTO.

I am fully aware of the fact that TypeScript can be "lied" to about the actual type of an object (whether it is an instance of a class or just a Plain Object). That's why, `map()` has a couple of overloads you can make use of:

```typescript
const user = this.mapper.map(registerUserDto, UserEntity); // this will be mapped correctly if registerUserDto is IN FACT an instance of RegisterUserDto.
```

You can always do the following:
```typescript
const user = this.mapper.map(registerUserDto, UserEntity, RegisterUserDto);
```
This way, AutoMapper will use the 3rd parameter as the Source model and will NOT try to infer the Source from `registerUserDto`. In this case, the 3rd parameter of `map()` will allow you to map from `registerUserDto` to `UserEntity` without having to map the `@Body()` before hand.

Give it a try and let me know if it works out for you. Thanks

**Comment by gpa** [comment]
Yes it works, thanks. I'm pretty sure I had it like this at some point but then tried to do the transform as early as possible to keep my services "pure" and strongly typed so I think that's how I ended up creating this issue.
Well this is a minor inconvenience at best. A small part of me still would liked to see a object to class feature and probably the inverse, especially since class-transformer is left unmainteined for a long time now and transforms unknown values as well by default which is annoying. But on the other hand I totally get the motivation behind keeping it object to object only and would be hesitant of extending it.
Feel free to close this issue and thanks for your work on this lib!
